FROM golang:1.17-alpine as pixiu-builder
WORKDIR /app
ARG VERSION
ENV GOPROXY=https://goproxy.cn
COPY ./go.mod ./
COPY ./go.sum ./
#RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${VERSION}'" -o pixiu ./cmd

FROM node:16.18.0-alpine as builder
LABEL MAINTAINER="PIXIU"
WORKDIR /build
COPY . .
RUN npm config set registry https://registry.npmmirror.com/ && npm install && npm run build

FROM nginx:alpine
LABEL MAINTAINER="PIXIU"
COPY --from=builder /build/dist /usr/share/nginx/html/pixiu
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=pixiu-builder /app/pixiu /app

